### ISSUE TITLE
Feature request: Plugin de boas vindas

### ISSUE THREAD

**Issue by iuriguilherme** [matehackers/matebot#42]
Lucas sugeriu que o MateBot enviasse uma mensagem a cada vez que alguém entra no grupo do telegram com o mapa das pedras.

**Comment by iuriguilherme** [comment]
Quem quiser responder este comentário pelo telegram e tiver autorizado o @GithubBot pode participar

**Comment by SubaruSama** [comment]
Gostaria de contribuir para esta feature. Irei dar uma lida de como funciona os bots no Telegram e no código do tg-matebot.

**Comment by iuriguilherme** [comment]
@SubaruSama não é necessário ler o código (até porque ele está neste momento sendo reescrito de forma incompatível com a branch master), é mais pras pessoas opinarem o que é que uma mensagem de boas vindas especificamente para o grupo do matehackers t.me/matehackerspoa deveria ter

**Comment by iuriguilherme** [comment]
Plugin welcome implementado com personalidades estável em **v0.1.6.11** bdf42611dc69cb350c69be3b10fc0647e992a266

**Comment by iuriguilherme** [comment]
@lfzawacki vê se o https://t.me/mate_obot tá recepcionando as pessoas conforme as tuas expectativas no https://t.me/matehackerspoa caso contrário podemos fazer uma versão específica para este grupo (em um plugin novo).
