### ISSUE TITLE
Dúvidas para Desenvolvimento

### ISSUE THREAD

**Issue by floriani-sci** [matehackers/matebot#60]
Olá, estou em dúvidas qual branch devo usar para estudar o código e possivelmente ajudar no projeto?

Verifiquei que no readme é informado para usar a **stable**, pórem essa está bem desatualizada, e na **main** está mais atual, qual devo usar?

Outra dúvida, subi o ambiente e estou recebendo a informação **telegram.error.Unauthorized: Unauthorized** , verifiquei o token e está ok, devo informar somente o token no arquivo **.env** ? Existe bastante divirgências entre as documentações informadas na branch **stable** e **main**.

**Comment by iuriguilherme** [comment]
@floriani-sci o README está parcialmente desatualizado porque a branch stable é baseada em uma versão antiga da branch master que usa o código também antigo com telepot.

eu mudei a branch padrão de master para main (por razões não técnicas) ao mesmo tempo que comecei a migrar de telepot pra flask/ptb.

e sim, o README está desatualizado. como eu lancei uma release beta, eu deveria documentar o processo de "ligar" o robô do jeito que é agora.

em relação à branch, parte da main e cria uma nova ( por exemplo git checkout -b contribuicoes)
