### ISSUE TITLE
Dúvidas para Desenvolvimento

### ISSUE THREAD

**Issue by cfloriani** [matehackers/matebot#61]
Olá, estou em dúvidas qual branch devo usar para estudar o código e possivelmente ajudar no projeto?
 
 Verifiquei que no readme é informado para usar a **stable**, pórem essa está bem desatualizada, e na **main** está mais atual, qual devo usar?
 
 Outra dúvida, subi o ambiente e estou recebendo a informação **telegram.error.Unauthorized: Unauthorized** , verifiquei o token e está ok, devo informar somente o token no arquivo **.env** ?  Existe bastante divirgências entre as documentações informadas na branch **stable** e **main**.

**Comment by iuriguilherme** [comment]
O **README** está desatualizado. A branch padrão e sempre mais avançada é a **main**. Tu pode começar por ela, mas é melhor mandar pull requests para outra branch, por exemplo: `git checkout -b novabranch`

A branch **stable** era (e pode continuar sendo) a última versão suficientemente estável do bot.

---

Em relação ao processo de teste, não está bem documentado mas de acordo com a última versão beta fefb6f632f12f93f4800792399a3eaab5c619622 tem que ter um arquivo **.env** com no mínimo as seguintes linhas:

```env
FLASK_APP=matebot.ptb_matebot
FLASK_ENV=production
BOTFATHER_TOKENS=['110201543:AAHdqTcvCH1vGWJxfSeofSAs0K5PALDsaw']
```
